class DataBreakfast {
  static List<String> listViewData = [
    "Rendang",
    "Peking Duck",
    "Beef Bulgogi",
    "Sushi",
    "Yaki Gyoza",
    "Pad Thai",
    "Roti Canai",
    "Hainan Chicken",
    "Nasi Daun",
    "Beef Lok Lak"
  ];
  static List<String> listViewDataImage = [
    "https://i0.wp.com/blog.duniamasak.com/wp-content/uploads/resep-rendang-asli-dp.jpg",
    "http://2.bp.blogspot.com/-B6ijdSocYKU/VLJ1fmp988I/AAAAAAAAAGE/61rQWWo2fHo/s1600/bebek-peking-3.jpg",
    "https://cdn.idntimes.com/content-images/community/2018/05/bulgogi-4-d0d49ae1193e84a5eb63c4e62ccd996a_600x400.jpg",
    "https://imgstaticcontent.lbb.in/lbbnew/wp-content/uploads/2017/07/20115010/Sushi_Deluxe_at_Sushi_Ten-600x400.jpg",
    "https://cdn.idntimes.com/content-images/community/2019/04/vegetarian-gyoza-dumplings-hero-42171d772b82383ce5eecdbc390ed51e_600x400.jpg",
    "https://media.awesomefoods.com/media/2017/07/pad-thai-1-600x400.jpg",
    "http://theganga.com.my/wp-content/uploads/2016/12/roti-planta.jpg",
    "https://cdn.idntimes.com/content-images/community/2018/02/nasi-hainan-2edd63a726d5369144b75e844ec2b9e6_600x400.jpg",
    "https://imgstaticcontent.lbb.in/lbbnew/wp-content/uploads/2017/09/02102328/01092017_ChopsticksSpiceMalabar_01-600x400.jpg",
    "https://static01.nyt.com/images/2014/04/17/dining/-Shaking-Beef-Bo-Luc-Lac/-Shaking-Beef-Bo-Luc-Lac-articleLarge.jpg"
  ];
  static List<String> listViewDataInfo = [
    "Rendang is a spicy meat dish which originated from the Minangkabau ethnic group of Indonesia, and is now commonly served across the country. One of the characteristic foods of Minangkabau culture, it is served at ceremonial occasions and to honour guests. Rendang is also commonly served among the Malay community in Malaysia, and is also popular in Singapore, Brunei, the southern Philippines and southern Thailand.Rendang is traditionally prepared by the Indonesian and Malaysian community during festive occasions such as traditional ceremonies, wedding feasts, and Hari Raya (Eid al-Fitr). Culinary experts often describe rendang as: 'West Sumatran caramelized beef curry'.",
    "Peking duck is a dish from Beijing (Peking) that has been prepared since the imperial era. The meat is characterized by its thin, crisp skin, with authentic versions of the dish serving mostly the skin and little meat, sliced in front of the diners by the cook. Ducks bred specially for the dish are slaughtered after 65 days and seasoned before being roasted in a closed or hung oven. The meat is often eaten with spring onion, cucumber and sweet bean sauce with pancakes rolled around the fillings. Sometimes pickled radish is also inside, and other sauces (like hoisin sauce) can be used.",
    "Bulgogi is one of Korea's most popular beef dishes that is made from thinly sliced sirloin or another prime cut of beef (rib eye). It is usually marinated in a mixture of soy sauce, sesame oil, black pepper, garlic, onions, ginger, and sugar for two to four hours to enhance the flavor and its tenderization. Bulgogi is traditionally grilled but broiling or pan-cooking is common as well. Whole cloves of garlic, sliced onions, and chopped green peppers are often grilled or cooked at the same time. It is often served to non-Koreans as a first taste of Korean cuisine.",
    "Sushi is a popular type of food that people around the world enjoy. Bits of fish wrapped in rice and seaweed, sushi is a fast and enjoyable snack or meal that you might love. Sushi has an interesting history, and there are several different types of sushi and preparation methods. Sushi originated in southeast Asia as a way to increase the shelf life of fish by placing it in fermenting rice. A 4th-century Chinese dictionary contains a character that means pickled fish with rice and salt. People discovered that when they placed salted fish into fermenting rice, the fish were preserved by a pickling process. This was the earliest type of sushi. When cooked rice begins its fermentation process, lactic acid bacilli are released. The bacilli interact with the salt to pickle the fish.",
    "Yaki gyoza is the most common type of cooking in Japan: the dumplings are fried on one side in a frying pan, then water mixed with a little cornstarch is added to the hot pan before being covered for a few minutes. It's this mode of cooking that sometimes attaches them to one another. These are hanetsuki gyoza , literally 'winged gyoza'. These gyoza are then served with the grilled side facing upwards. Traditionally, gyoza are stuffed with minced pork mixed with green onions, spring onion, cabbage, ginger, and garlic. But nowadays, some establishments offer alternate recipes  - such as shrimp or seafood - and experiment with different flavors. You can even find cheese gyoza in some specialty restaurants!",
    "Pad Thai is typical street fare across Thailand—and it's probably the #1 order at your local Thai restaurant. In fact, this popular stir-fried noodle dish is the national dish of Thailand. But what exactly is it about Pad Thai that makes it so delicious? Bold, umami flavors and a variety of textures make Pad Thai into a comforting meal that everyone can love. Let's take a closer look at this beloved Thai dish. The basic ingredients in a traditional Pad Thai are rice noodles stir-fried with tofu, eggs, and a sauce made with tamarind paste, fish sauce, dried shrimp, garlic, chiles, and palm sugar (which is often less refined than cane sugar). Pad Thai is characterized by rich, vibrant flavors, from funky (fish sauce and dried shrimp), to sour (fresh tamarind paste), to sweet (palm sugar).",
    "Roti canai , also known as roti cane or roti parotta, is an Indian-influenced flatbread dish found in several countries in Southeast Asia, including Malaysia, Brunei, Indonesia and Singapore. It is usually served with dal or other types of curry, but can also be cooked in a range of sweet or savoury variations made with a variety of ingredients such as sardines, meat, egg, or cheese. Roti canai is a popular breakfast and snack dish in Malaysia, and one of the most famous examples of Malaysian Indian cuisine. It is said that the dish was brought over from India by Indian Muslims, also known as 'Mamaks' in Malaysia, and is served in Mamak stalls located in both rural and urban Malaysia. It is considered as a variation of parotta but it does not exist in India. The closest kin to roti canai is believed to be Malabar parotta.",
    "Hainanese chicken rice is a dish of poached chicken and seasoned rice, served with chilli sauce and usually comes with cucumber garnishes. It was created by immigrants from Hainan in southern China and adapted from the Hainanese dish Wenchang chicken. It is considered one of the national dishes of Singapore and is most commonly associated with Singaporean cuisine but is also seen throughout Southeast Asia, particularly Malaysia where it is a culinary staple.",
    "Banana leaf rice is a traditional method of serving rice dishes in South Indian cuisine. Due to the migration of South Indians, banana leaf rice can also be found in areas with significant ethnic South Indian diaspora such as Malaysia and Singapore. In banana leaf meals, white rice (or parboiled rice in authentic South Indian restaurants) is served on a banana leaf with an assortment of vegetables, pickles, appalam and other regional condiments (usually sour, salty or spicy). The banana leaf acts as a disposable plate and it in itself is not consumed. The choice of banana leaves is mainly due to the broad leaves as well as to the ubiquity of the plant in South India. Typically, only vegetarian gravy (e.g. sambar) will be served on the rice as it is meant to be a traditional vegetarian dish. However, sometimes boiled eggs, curried or fried meat or seafood are served as well. Traditionally, there will be two servings of rice with the first being served with gravy, side dishes and condiments whilst the second serving will be just rice with curd as a palate cleanser.",
    "Here is one of the emblematic dishes of Cambodia: beef lok lak. Lok lak or loc lac (ឡុកឡាក់) appears on the menu of most restaurants in Cambodia but also abroad. It is indeed a dish that delights the palate of Westerners and has therefore exported very well. It consists in beef cut into pieces, marinated and then sautéed in a wok before being served on a bed of green salad with slices of tomatoes and cucumber that bring freshness to the dish. It is accompanied by rice as well as a lime and black pepper sauce in which the meat can be dipped before eating. A culinary journey! To complete the trip to Cambodia, I suggest you also try kdam chaa, stir-fried crab with green pepper, bai sach chrouk, grilled pork rice, ang dtray-meuk, grilled squid, or the famous amok trei, fish with coconut milk and lemongrass steamed in a banana leaf."
  ];
}
class DataDesert {
  static List<String> listViewData = [
    "Alfajores",
    "Apfelstrudel",
    "Baklava",
    "Black Forest",
    "Borma",
    "Brownies",
    "Cannoli",
    "Cardamom Buns",
    "Choco Chip",
    "Choco Mousse"
  ];
  static List<String> listViewDataImage = [
    "http://www.confessionsofachocoholic.com/wp-content/uploads/2014/03/alfajor-cookies.jpg",
    "https://cdn.idntimes.com/content-images/community/2019/05/images-1-98b5282af96ee48b07cb6ec31b5d5d26.jpeg",
    "https://cdn.idntimes.com/content-images/community/2019/05/fistikli-baklava-800x800-617163ad19db7fb9d0877181aaa1303e_600x400.jpg",
    "https://www.recipegirl.com/wp-content/uploads/2017/07/IMG_3995-black-forest-cake-horizontal-600x400.jpg",
    "https://s3-media4.fl.yelpcdn.com/bphoto/2RBvlO-LgkNp1Mo8H4_nrg/l.jpg",
    "https://www.afarmgirlsdabbles.com/wp-content/uploads/2012/01/fudgy-brownie-hearts_AFarmgirlsDabbles_AFD-6-600x400.jpg",
    "https://i1.wp.com/anitalianinmykitchen.com/wp-content/uploads/2016/11/baked-cannoli-picture-1-of-1.jpg",
    "https://ediblesanfrancisco.com/wp-content/uploads/2018/10/swedish-cinnamon-knot.jpg",
    "https://www.loveandoliveoil.com/wp-content/uploads/2014/03/stuffed-pb-cookies-FEAT-600x400.jpg",
    "https://www.thepeppermillinc.com/uploads/images/products/92fe06b1-6aac-4006-8def-5404fb68482a.jpg",
  ];
  static List<String> listViewDataInfo = [
    "Step into a neighborhood bakery from Argentina to Peru, and you're likely to find these tender, filled cookies piled high behind the counter. The crumbly bite of shortbread gives way to a sweet layer of dulce de leche, a caramel-like candy made by gently cooking sweetened milk until it turns into a rich, mellow treat. The very simplicity of the cookies has proved to be the perfect base for creative cooks across Latin America. Try versions that are dunked in dark chocolate, coated in a sweet layer of white chocolate, rolled in coconut and dressed up with spices, or opt for the classic -- it's among the world's most comforting snacks.",
    "For a floury lesson in gluten's architectural wonders, whip up a batch of traditional strudel dough. The real thing is stretched -- not rolled -- into an improbably thin sheet; according to legend, it should be transparent enough to read a newspaper through. Once extended, the delicate dough is wrapped around a sweet, apple filling that's enriched with buttery fried breadcrumbs, raisins and sometimes walnuts. The delicious result can be found in pastry shops around the world, but for the classic experience, head to Vienna's Café Korb for a slice followed by a lush cup of cream-topped Viennese coffee.",
    "Dozens of delicate layers melt into a single tender bite in this syrupy confection, which is among the sweetest legacies of the Ottoman Empire. While it remains a sought-after treat through the Levant, Balkans, the Caucasus and North Africa -- regions that were once ruled from Constantinople -- the spiritual home of baklava is surely the modern-day country of Turkey. There, pastry shops serve great trays sliced into diamonds, filled with ground nuts and dripping with honeyed syrup. This is just the most famous of the Ottoman Empire's syrup-soaked pastries, but it's snagged the limelight for good reason. With a simple list of ingredients and endless variations, it easily ranks among the world's most tempting treats.",
    "Along with fairy tales and mountain-top castles, Germany's Black Forest region is known as the namesake -- if not the origin -- of the country's most luscious cake. Dark rounds of chocolate cake are doused in a cherry syrup spiked with kirschwasser, a sour cherry brandy, then stacked atop a thin, chocolate base with deep layers of whipped cream and fresh cherries. If that wasn't flavor enough, the whole thing is swathed in more cream, dusted with shaved chocolate and studded with cherries. The resulting cake is a frothy dream dessert that's the star of pastry cases around Germany, where it's known as a Schwarzwälder Kirschtorte.",
    "Threads of crisp, golden knafeh dough wrap around a rich nut filling in this sweet dessert, which is an elegant and aromatic relative of baklava. Unlike baklava, borma is often fried, adding an extra infusion of flavor and a crisp texture that stands up to a sugary bath in flavored syrup. And while baklava hides its filling inside a modest layer of filo dough, borma is rolled and sliced, showing off a cross-section of colorful pistachios, pale pine nuts or walnuts. That eye-catching presentation makes borma especially popular as a present. Pastry shops across the Middle East and Turkey tempt passers-by with piles of borma stacked high on enormous platters.",
    "Fudgy or cakey? Corner piece or slice from the middle? Aficionados of this beloved American sweet are sure to have a take on the best -- and worst -- way to make a brownie. One of the earliest recipes appeared in Fannie Farmer's 1906 'Boston Cooking School Cook Book,' using the unsweetened chocolate that lends brownies a fudgy texture. In more than a century of brownie making, they've become a mainstay treat, the base for sundaes and a seriously addictive ice cream flavor. Even the actress Katharine Hepburn had an opinion on how to bake them, and an old story holds that the glamorous star once dispensed the following advice: 'Never quit, be yourself and don't put too much flour in your brownies.'",
    "A shattering-crisp shell gives way to a creamy cheese filling in this Sicilian classic, whose roots reach deep into the island's diverse culinary history. With origins at the wild Carnival celebrations at Palermo, the traditional cannolo is filled with silky-smooth ricotta cheese made from sheep's milk. Taste that rich filling for evidence of the Arab influence that infuses Sicilian cuisine: The candied citrus that often flavors the creamy interior remains beloved throughout the Middle East.",
    "October 4 might be Cinnamon Bun Day on the Swedish calendar, but many bun aficionados insist that the aromatic cardamom version outshines cinnamon's more assertive charms. One of a family of vetebullar, or wheat buns, cardamom buns are best enjoyed as a part of fika, the coffee break that comes twice daily in many Swedish workplaces. While a freshly baked cardamom bun is a memorable treat, it's also a simple and comforting one. In a classic recipe from author Johanna Kindvall, crushed cardamom seeds are stirred into lightly enriched, yeasted dough, then rolled up with a sweet layer of sugar and spice. For the perfect fika, whip up a batch of cardamom buns, brew some strong coffee and call a friend, since the iconic Swedish coffee break is as much about talking as it is about treats.",
    "The quintessential American treat is deceptively simple: a basic, creamed-butter cookie recipe turns out to have endless subtle variations that produc dramatically different results. Whatever your favorite version, a perfect chocolate chip cookie is a delicate balance of textures and flavors. A crispy rim gives way to a tender, melting center, and the buttery sweetness of the dough sets off the slight edge of bittersweet chocolate and brown sugar. Legend has it that the chocolate chip cookie has its origins in a happy accident, when Massachusetts inn owner Ruth Wakefield stirred chopped chocolate into her cookie dough in an attempt to make uniformly chocolatey cookies. Her brand-new recipe was published in a Boston newspaper, and the rest was pastry history.",
    "An airy confection made with just a handful of ingredients, chocolate mousse is a delicious paradox: the richer it is, the lighter it seems. Gallic chefs have been whipping up chocolate mousse -- the word means 'foam' in French -- for at least a few hundred years, but the quest for foamy chocolate is much older. Among the Olmec, Maya and Aztec peoples who consumed chocolate long before contact with Europeans, a hefty layer of foam was considered the height of good taste, and ancient codices depict cooks pouring chocolate from several feet in the air to create a froth."
  ];
}